## Project information
site_name: OpsFusionLabs
site_url: https://opsfusionlabs.github.io/opsfusionlabs/
site_description: Devops 

## Repository
repo_name: OpsFusionLabs
repo_url: https://github.com/opsfusionlabs/opsfusionlabs.git


theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    # - toc.integrate
    - navigation.prune
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

extra_css:
  - stylesheets/extra.css

plugins:
  # - social
  - search
  - glightbox

nav:
- Home: 'index.md'
- Installation Guides :
    - 'Docker Installation': 'Installations/Install-Docker-Engine-on-RHEL.md'
    - 'Jenkins Installation': 'Installations/Jenkins Installation.md'
    - 'Webserver Installation': Installations/Httpd Webserver.md
    - 'Argo Cd': Installations/Argo Cd.md
- Integration :
    - 'Docker Integration': 'Tool-integrations/Integrate-docker-with-jenkins.md'
    - 'Sonarqube Integration': 'Tool-integrations/Integrate-sonarqube-jenkins.md'
- Containerization :
    - 'Managing Docker Containers': 'Installations/Docker/Managing Docker Containers.md'
- Kubernetes : 
    - 'Cluster Architecture' : 'Kubernetes/Cluster Architecture.md'
    - 'Cluster Installaion' : 'Kubernetes/Cluster Installation.md'
    - 'Working with Pods' : 'Kubernetes/Working with Pods.md'
    - 'Working With ReplicaSets' : Kubernetes/Working with ReplicaSets.md
    - 'Working with Deployments'  : Kubernetes/Working with Deployments.md
    - 'Working with Namespace' : Kubernetes/Working with Namesapce.md
    - 'Working with Services' : Kubernetes/Working with Services.md
    - 'Storage': Kubernetes/Storage.md
    - 'Ephemeral Storage': 
          - emptyDir: Kubernetes/emptyDir.md
          - ConfigMap: Kubernetes/ConfigMap.md
 
        
      
- Version Control System: 
    - 'Git': 'Git/Git.md'
    - 'User Configuration': 'Git/Git Credentials Setup.md'
    - 'Initial Git Work flow': 'Git/Workflow.md'
    - 'Git Branching': 'Git/Branches.md'

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/james-willett
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheJamesWillett
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/willettjames/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: _span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html


        

copyright: |
  &copy; 2024 <a href="#"  target="_blank" rel="noopener">OpsFusionlabs</a>