site_name: OpsFusionLabs
# site_url: https://james-willett.github.io/mkdocs-material-youtube-tutorial/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
  # - social
  - search

nav:
- Home: 'index.md'
- Installation Guides :
    - 'Docker Installation': 'Installations/Install-Docker-Engine-on-RHEL.md'
    - 'Jenkins Installation': 'Installations/Jenkins Installation.md'
    - 'Webserver Installation': Installations/Httpd Webserver.md
    - 'Argo Cd': Installations/Argo Cd.md
- Integration :
    - 'Docker Integration': 'Tool-integrations/Integrate-docker-with-jenkins.md'
    - 'Sonarqube Integration': 'Tool-integrations/Integrate-sonarqube-jenkins.md'
- Containerization :
    - 'Managing Docker Containers': 'Installations/Docker/Managing Docker Containers.md'
- Kubernetes : 
    - 'Cluster Architecture' : 'Kubernetes/Cluster Architecture.md'
    - 'Cluster Installaion' : 'Kubernetes/Cluster Installation.md'
    - 'Working with Pods' : 'Kubernetes/Working with Pods.md'
- SCM: 
    - 'Git': 'Git/Git.md'
    - 'User Configuration': 'Git/Git Credentials Setup.md'
    - 'Initial Git Work flow': 'Git/Git Work flow.md'

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/james-willett
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheJamesWillett
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/willettjames/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

        

copyright: |
  &copy; 2024 <a href="#"  target="_blank" rel="noopener">OpsFusionlabs</a>